### ISSUE TITLE
about ページ

### ISSUE THREAD

**Issue by mikakane** [chatbox-inc/chatbox2020#120]
http://localhost:3000/about

- [x] 画像の差込
- [x]  ※ビルの1階にCoCo壱があります -> ※1階のCoCo壱が目印の建物です。
- [x] 交通機関、「X 番出口」の表記削除
- [x] 「天満橋パークビル 5F」 の表記に変更
- [x] google map を target brank に
- [x] 978~660px でみたときに トップの会社概要の表記がパツパツなのでpaddingとって調整してください
コーディング
![スクリーンショット 2020-07-22 14 12 54](https://user-images.githubusercontent.com/1859101/88136983-7e1e6980-cc25-11ea-9854-b73c3a99d303.png)

**Comment by mikakane** [comment]
about に fixed ニュース通知が出てないのはなぜ？

**Comment by ririko25** [comment]
- 画像の差込に伴う画像選定
- fixedニュースの通知が出る画面の再確認

**Comment by ririko25** [comment]
@mikaryna 

画像差込以外対応お願いします！

**Comment by ririko25** [comment]
@mikaryna 
以下対応お願いします。

- [ ] 現在仮画像になている箇所に以下の画像差込お願いします！

![about_img@2x](https://user-images.githubusercontent.com/29808916/88503477-cc0fe480-d00c-11ea-9596-f475a78457ef.png)
