### ISSUE TITLE
トップページ タグ部分の表示、デザイン修正

### ISSUE THREAD

**Issue by mikakane** [chatbox-inc/chatbox2020#121]
PC / SP ともにこれくらいの大きさでインパクト取れるように

![スクリーンショット 2020-07-22 14 14 57](https://user-images.githubusercontent.com/1859101/88137087-c50c5f00-cc25-11ea-80b0-abe5cd78c2e8.png)

スマホ表示では折返しが汚いので、600 px 以下くらいで消してもよい

**Comment by ririko25** [comment]
デザイン修正　

内容：TOPページ_creation、talking、enjoyの赤文字サイズ変更

creation
![スクリーンショット 2020-07-22 16 13 54](https://user-images.githubusercontent.com/29808916/88146184-7c10d680-cc36-11ea-9d58-b3c39cbe6979.png)

talking
![スクリーンショット 2020-07-22 16 14 01](https://user-images.githubusercontent.com/29808916/88146194-7fa45d80-cc36-11ea-8ec1-99e5ed44d2b5.png)

enjoy
![スクリーンショット 2020-07-22 16 14 07](https://user-images.githubusercontent.com/29808916/88146199-8206b780-cc36-11ea-9d84-e78ee047f9a4.png)



上記デザインOKだったらコーディング修正に進みます。

**Comment by ririko25** [comment]
@mikaryna 

以下の対応お願いします！

- [ ]  文字サイズと行間を以下のカンプに合わせて変更お願いします。
https://xd.adobe.com/view/2421e249-9f0c-400f-a3ba-bc8358d4f075-7172/screen/85f78aed-b8d3-4f06-8ab5-59e8466776ca/

- [ ] 785px以下では文字を非表示に
