### ISSUE TITLE
トップページ修正

### ISSUE THREAD

**Issue by mikakane** [chatbox-inc/chatbox2020#122]
- 採用情報へ、を target=blank へ
-フッターから実績紹介の部分コメントアウト ( 別途 Issue 立てて

**Comment by ririko25** [comment]
@mikakane 

実績紹介部分コメントアウトに関してですが、
今は表示させないという認識で間違いないでしょうか？

**Comment by ririko25** [comment]
@mikaryna 

- [ ] 採用情報セクション_採用情報へボタン(wantedlyに遷移するボタン)を target=blank へ
- [ ] フッター_実績紹介の部分コメントアウト
