### ISSUE TITLE
お知らせの修正

### ISSUE THREAD

**Issue by mikakane** [chatbox-inc/chatbox2020#123]
http://localhost:3000/news/48OCIBaXWvyHS0t0Nqsd

- [x] 改行は反映したい。
- [x] URL は リンク形式で見せたい

- [x] 画面遷移時の見え方がキモチワルイので fetch で実装してほしい

**Comment by mikakane** [comment]
お知らせページのお問い合わせ遷移先が未設定。これ共通化していない？

**Comment by mikakane** [comment]
![スクリーンショット 2020-07-22 14 27 41](https://user-images.githubusercontent.com/1859101/88137898-87103a80-cc27-11ea-929d-06643396a2df.png)

600 px くらいで一覧画面見たときの初期表示がバグってる

**Comment by mikakane** [comment]
一覧画面もお問い合わせリンク未設定

**Comment by mikakane** [comment]
従業員数 30名（アルバイト含む
に変更

**Comment by ririko25** [comment]
これはaboutページの内容？

> 従業員数 30名（アルバイト含む
に変更
