### ISSUE TITLE
【コーディング】TOPページ_タイトル部分の装飾修正

### ISSUE THREAD

**Issue by mikakane** [chatbox-inc/chatbox2020#126]
![スクリーンショット 2020-07-22 14 29 21](https://user-images.githubusercontent.com/1859101/88138025-c6d72200-cc27-11ea-9fb1-d60ab645b375.png)

赤い文字と黒い文字の隙間がだいぶ空いているのでこれを詰めれないか

**Comment by ririko25** [comment]
タイトル部分の一文字目と2文字目の間の調整お願いします

コーディング
![スクリーンショット 2020-07-22 15 19 07](https://user-images.githubusercontent.com/29808916/88141559-cf7f2680-cc2e-11ea-8796-9ce97d9eb199.png)


現行サイト
![スクリーンショット 2020-07-22 15 19 09](https://user-images.githubusercontent.com/29808916/88141553-cdb56300-cc2e-11ea-9539-8eabcce9bb7f.png)
