### ISSUE TITLE
【コーディング】TOPページ_メンバーセクション_背景色調整

### ISSUE THREAD

**Issue by mikakane** [chatbox-inc/chatbox2020#128]
![スクリーンショット 2020-07-22 14 30 11](https://user-images.githubusercontent.com/1859101/88138083-ec642b80-cc27-11ea-8001-077779dd3176.png)

背景のしゃしｎ写真と文字がかぶって見えない
グラデーションの方向を垂直に変更

**Comment by ririko25** [comment]
@mikakane 

現行サイトとほぼ同じ感じにしてもらったのですが、見えづらいでしょうか？

現行サイト
![スクリーンショット 2020-07-22 15 05 01](https://user-images.githubusercontent.com/29808916/88140450-bb3a2a00-cc2c-11ea-9c0b-d52aad510e7d.png)

リニューアルサイト
![スクリーンショット 2020-07-22 15 04 44](https://user-images.githubusercontent.com/29808916/88140436-b2495880-cc2c-11ea-98ab-951bd2fed5dc.png)




あとメンバー修正するのであれば、

aboutセクションも同じグラデーション使ってるのでこちらも修正しますか？
![スクリーンショット 2020-07-22 15 10 31](https://user-images.githubusercontent.com/29808916/88140951-a1e5ad80-cc2d-11ea-8255-5f3a3c7c4e47.png)




一旦、垂直方向にグラデーションかけたバージョン作ってみました

メンバー

![スクリーンショット 2020-07-22 15 14 52](https://user-images.githubusercontent.com/29808916/88141216-20424f80-cc2e-11ea-818c-aa38fb927f7b.png)

**Comment by ririko25** [comment]
@Mana0-ui 
一旦メンバーセクションのグラデーションを垂直方向に変更お願いします。
