### ISSUE TITLE
【コーディング】会社概要

### ISSUE THREAD

**Issue by NaNagaiShiho** [chatbox-inc/chatbox2020#13]
## 概要
会社概要の新規ページ作成お願いします

## カンプ
PC
https://xd.adobe.com/view/4f8e11c6-bc5e-44e5-a189-926caab9b7f7-1add/screen/ea0b6d9d-989d-4901-883a-856c31274c26/pc-
SP
https://xd.adobe.com/view/4f8e11c6-bc5e-44e5-a189-926caab9b7f7-1add/screen/605b5844-ee3b-4c5a-9a72-8c0a16c2e859/sp-

## 画像データ
用意ができていないので仮で何かお願いします

**Comment by ririko25** [comment]
以下の修正対応お願いします！

## pc

- [ ] ボタンのサイズ調整お願いします！

コーディング
![スクリーンショット 2020-07-17 8 59 58](https://user-images.githubusercontent.com/29808916/87733915-14105980-c80c-11ea-88a0-e55596e385b1.png)

カンプ
![スクリーンショット 2020-07-17 9 01 30](https://user-images.githubusercontent.com/29808916/87733923-2094b200-c80c-11ea-93da-41fde93832f0.png)


## sp

- [ ]  chatboxについてセクションの見出しとテキストの間のスペースが空いているので調整お願いします！

コーディング
![スクリーンショット 2020-07-17 9 00 42](https://user-images.githubusercontent.com/29808916/87733981-40c47100-c80c-11ea-9d39-65bc0a3825f9.png)

カンプ
![スクリーンショット 2020-07-17 9 02 43](https://user-images.githubusercontent.com/29808916/87733998-4a4dd900-c80c-11ea-98f3-cd54fbbcbe29.png)
