### ISSUE TITLE
【コーディング】お知らせ_一覧

### ISSUE THREAD

**Issue by NaNagaiShiho** [chatbox-inc/chatbox2020#14]
## 概要
お知らせ一覧ページのコーディングをお願いします！

## カンプ、画像素材
以下のスプレットシートに記載しておりますので、こちらご確認ください！
https://docs.google.com/spreadsheets/d/1SgBUxJx5kTI3vjju8Njim3kMGehMlKUBvGW2P1qqzIo/edit#gid=218982908

## 仕様
- READMEをご確認ください！
https://github.com/chatbox-inc/chatbox2020
- Tailwind CSSを使ってのコーディングになります。
tailwindの使い方は以下にまとめてもらっています！
https://tailwindcss.com/docs/installation/

**Comment by ririko25** [comment]
以下の修正対応お願いします！

作業内容が過去データに準拠したものになっていたので、確認してもらっているxdデータが過去のかもしれないです！
スプレットシートに新しいのが貼ってありますのでこちらご確認ください！
https://docs.google.com/spreadsheets/d/1SgBUxJx5kTI3vjju8Njim3kMGehMlKUBvGW2P1qqzIo/edit#gid=218982908

## pc

- [ ] 日付部分が西暦まで出るように変更お願いします！

コーディング
![スクリーンショット 2020-07-17 9 08 18](https://user-images.githubusercontent.com/29808916/87734429-8fbed600-c80d-11ea-9bb9-bdc5255ad3af.png)


カンプ
<img width="143" alt="スクリーンショット 2020-07-17 9 05 48" src="https://user-images.githubusercontent.com/29808916/87734382-728a0780-c80d-11ea-92a4-973261ba30de.png">


## sp

- [ ]  sp版日付のデザインとかが違うので、こちらも変更お願いします！

コーディング
![スクリーンショット 2020-07-17 9 06 58](https://user-images.githubusercontent.com/29808916/87734424-8cc3e580-c80d-11ea-8b86-79d7ac6d9ed7.png)

カンプ
<img width="305" alt="スクリーンショット 2020-07-17 9 07 03" src="https://user-images.githubusercontent.com/29808916/87734435-93525d00-c80d-11ea-92f3-af134dd5ea4d.png">
