### ISSUE TITLE
【コーディング】全体修正内容

### ISSUE THREAD

**Issue by ririko25** [chatbox-inc/chatbox2020#145]
デザインとコーディング画面見比べて修正が必要な箇所があればコメントに記入してください！

ボタンがどのページからも遷移できるかどうかの確認もお願いします！

コーディング画面
https://chatbox2020.netlify.app/

デザインカンプ
https://xd.adobe.com/view/2421e249-9f0c-400f-a3ba-bc8358d4f075-7172/flow

確認画面一覧
https://docs.google.com/spreadsheets/d/1SgBUxJx5kTI3vjju8Njim3kMGehMlKUBvGW2P1qqzIo/edit#gid=218982908

**Comment by ma-sa321** [comment]
## Topページ(PC)のデザインと実装確認
- 実装された方には"Us"がない．
![スクリーンショット 2020-07-30 13 06 44](https://user-images.githubusercontent.com/36505606/88880188-0eccf900-d267-11ea-9334-8f60261838b3.png)

- 現行サイト通りとありますが，表記が異なっている．
![スクリーンショット 2020-07-30 13 04 51](https://user-images.githubusercontent.com/36505606/88880265-3d4ad400-d267-11ea-810d-a20ae573ec6f.png)

- フォントの太さが異なる．
![スクリーンショット 2020-07-30 13 04 18](https://user-images.githubusercontent.com/36505606/88880376-8dc23180-d267-11ea-8591-e7a26f494276.png)

- 現行サイト通りとありますが，透過方向が異なる．
![スクリーンショット 2020-07-30 13 01 15](https://user-images.githubusercontent.com/36505606/88880461-bb0edf80-d267-11ea-87c4-540f0ffdee6b.png)

- 幅980以下で表示が変わる．
![スクリーンショット 2020-07-30 13 02 12](https://user-images.githubusercontent.com/36505606/88880538-f5787c80-d267-11ea-9222-5f358d8ea599.png)

**Comment by ma-sa321** [comment]
## Topページ(SP)のデザインと実装確認
- 表示がない．
![スクリーンショット 2020-07-30 13 32 34](https://user-images.githubusercontent.com/36505606/88881209-cf53dc00-d269-11ea-8b8a-23118205ae3b.png)

- 横線が入っている．
![スクリーンショット 2020-07-30 13 33 35](https://user-images.githubusercontent.com/36505606/88881230-db3f9e00-d269-11ea-9d3b-766272872dfa.png)

**Comment by ma-sa321** [comment]
Contactページ(PC&SP)の実装(写真左)とデザイン(写真右)確認
- お問い合わせはこちらが表示されている．
![スクリーンショット 2020-07-30 13 44 25](https://user-images.githubusercontent.com/36505606/88881665-f1019300-d26a-11ea-99ca-bb2a63e1b9e2.png)

- "Wev"になっている．
- SP版に切り替わっても，横二列になっている．
![スクリーンショット 2020-07-30 13 42 31](https://user-images.githubusercontent.com/36505606/88881735-1ababa00-d26b-11ea-998c-231592355e01.png)

**Comment by ma-sa321** [comment]
## どのページにもある修正点
- 横線が入っている．
![スクリーンショット 2020-07-30 13 33 35](https://user-images.githubusercontent.com/36505606/88881230-db3f9e00-d269-11ea-9d3b-766272872dfa.png)

**Comment by ma-sa321** [comment]
## Newsページ(PC&SP)の実装とデザイン確認
- お問い合わせフォームに移動後，backで戻ってくると項目が表示されない．
![スクリーンショット 2020-07-30 14 15 08](https://user-images.githubusercontent.com/36505606/88883404-39bb4b00-d26f-11ea-883c-ded0f60b092b.png)
