### ISSUE TITLE
【コーディング】お知らせ_詳細

### ISSUE THREAD

**Issue by NaNagaiShiho** [chatbox-inc/chatbox2020#15]
## 概要
お知らせ詳細ページのコーディングをお願いします！

## カンプ、画像素材
以下のスプレットシートに記載しておりますので、こちらご確認ください！
https://docs.google.com/spreadsheets/d/1C22MDjmDbVZmhbzJpexhIjkaOW6pGaDzoPjOsT2HhSA/edit#gid=0

## 仕様
- READMEをご確認ください！
https://github.com/chatbox-inc/chatbox2020
- Tailwind CSSを使ってのコーディングになります。
tailwindの使い方は以下にまとめてもらっています！
https://tailwindcss.com/docs/installation/

**Comment by ririko25** [comment]
以下の修正対応お願いします！

## pc

- [ ] このページのみコンテナ幅が700pxになるので調整お願いします！
tailwindの関係で調整難しそうだったらコメントください！

コーディング
![スクリーンショット 2020-07-17 9 17 28](https://user-images.githubusercontent.com/29808916/87734769-8f730a80-c80e-11ea-8a54-8500ae3d21f9.png)

カンプ
<img width="409" alt="スクリーンショット 2020-07-17 9 19 19" src="https://user-images.githubusercontent.com/29808916/87734793-9c8ff980-c80e-11ea-96ce-4678e71a6796.png">


## sp

- [ ]  日付のデザインがpcとspで違うので調整お願いします！

コーディング
![スクリーンショット 2020-07-17 9 18 20](https://user-images.githubusercontent.com/29808916/87734947-027c8100-c80f-11ea-9006-8e0d2e0d0983.png)

カンプ
<img width="209" alt="スクリーンショット 2020-07-17 9 22 28" src="https://user-images.githubusercontent.com/29808916/87734965-0d371600-c80f-11ea-9986-4676d9c5f3be.png">

- [ ] spの時の本文テキストのpx数を14pxに変更お願いします！

コーディング
![スクリーンショット 2020-07-17 9 18 38](https://user-images.githubusercontent.com/29808916/87735012-35267980-c80f-11ea-86e7-98e59f95a2e8.png)

カンプ
<img width="290" alt="スクリーンショット 2020-07-17 9 18 48" src="https://user-images.githubusercontent.com/29808916/87735020-3a83c400-c80f-11ea-9de6-1f7526320c21.png">
