### ISSUE TITLE
お知らせページのバグ修正

### ISSUE THREAD

**Issue by mikaryna** [chatbox-inc/chatbox2020#160]
お知らせページのお知らせ詳細画面でリロードするとこのようなエラー画面になります
ローカルの環境では大丈夫ですが、Netlifyでみた時にエラーになるのでそちらの調査と対応お願いします
<br>
![image](https://user-images.githubusercontent.com/61623506/89620195-47557e00-d8ca-11ea-970f-deae6213c577.png)

**Comment by ririko25** [comment]
本番環境URLで確認したら大丈夫そうだったので一旦closeします！
