### ISSUE TITLE
Ligthhouse 対応

### ISSUE THREAD

**Issue by mikakane** [chatbox-inc/chatbox2020#163]
Ligthhouse 対応

https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fchatbox2020-26423.web.app%2F

_Originally posted by @mikakane in https://github.com/chatbox-inc/chatbox2020/issues/161#issuecomment-670928120_

**Comment by mikaryna** [comment]
## TOPページ
- [ ] htmlにlang属性を追加
- [ ] 画像にalt属性を追加
- [ ] target="_blank"を使用したリンクにrel="noopener"をつける
- [ ] わかりづらいリンクにaria-label属性をつける
## ABOUTページ
- [ ] <iFrame>要素にtitile属性をつける
## CONTACTページ
- [ ]
