### ISSUE TITLE
【コーディング】フッタ

### ISSUE THREAD

**Issue by NaNagaiShiho** [chatbox-inc/chatbox2020#18]
## 概要
全体フッターのコーディングをお願いします！ 

Tailwind CSSを使ってコーディングお願いします。

## 資料
https://tailwindcss.com/docs/installation/

## カンプ、画像素材
以下のスプレットシートに記載しておりますので、こちらご確認ください！

TOPのデザインカンプに載っているpcとspのデザインが正です

https://docs.google.com/spreadsheets/d/1C22MDjmDbVZmhbzJpexhIjkaOW6pGaDzoPjOsT2HhSA/edit#gid=0

**Comment by ririko25** [comment]
以下の修正対応をお願い致します！

## PC

- [ ] コンテナからはみ出してるっぽい？ので現行サイトの挙動に合わせてコーディングお願いします！

コーディング
![スクリーンショット 2020-07-15 15 44 23](https://user-images.githubusercontent.com/29808916/87512951-dd72fb80-c6b2-11ea-95fe-3fba9eca12cf.png)

カンプ
<img width="840" alt="スクリーンショット 2020-07-15 15 44 26" src="https://user-images.githubusercontent.com/29808916/87512965-e532a000-c6b2-11ea-9dcd-13e0898bd09b.png">

**Comment by ririko25** [comment]
以下の修正お願いします！

## sp

- [ ] お知らせのバーがsp時にちょっと被ってるので、フッタのしたかぶらない程度に調整お願いします！

<img width="462" alt="スクリーンショット 2020-07-20 13 49 16" src="https://user-images.githubusercontent.com/29808916/87900604-d3c10d80-ca8f-11ea-9640-fe76a3afbb73.png">

**Comment by ririko25** [comment]
以下の修正対応お願いします！

## pc&sp

- [ ] お知らせバーの高さ分下に領域を広げてもらったのですが、背景色が白になっているので、こちらフッタのピンク？カラーにしてあげてください！

コーディング
お知らせバーがある状態
![スクリーンショット 2020-07-21 10 49 21](https://user-images.githubusercontent.com/29808916/88003545-13dfc900-cb40-11ea-86bc-b51942874016.png)

ない状態
![スクリーンショット 2020-07-21 10 51 36](https://user-images.githubusercontent.com/29808916/88003576-29ed8980-cb40-11ea-9bc0-06e0a903f65a.png)
