### ISSUE TITLE
w38_リリース前追加修正

### ISSUE THREAD

**Issue by ririko25** [chatbox-inc/chatbox2020#181]
- [x] newsのページ削除
- [x] 固定のnewsバーも削除
- [ ] お問い合わせが正常に動作するように修正
- [x] お問い合わせ後フォームの内容が消えるように修正

**Comment by manak1** [comment]
お問い合わせの送信ですが、請求先アカウントが設定されていないため、外部ネットワークにアクセスできずエラーが起きているようです。
<img width="513" alt="スクリーンショット 2020-09-30 14 52 17" src="https://user-images.githubusercontent.com/32151765/94647965-8b925700-032c-11eb-91b4-9afa8c9bd73b.png">
