### ISSUE TITLE
[コーディング] TOP_recruitセクション

### ISSUE THREAD

**Issue by manak1** [chatbox-inc/chatbox2020#22]
## 概要
TOPページ Recruitセクション /pages/-CRecruit.vue
/pages/-CIntro.vue を参考にTailwind CSSを使ってコーディングお願いします。

## 資料
https://tailwindcss.com/docs/installation/

## デザインデータ
PC時
https://xd.adobe.com/view/4f8e11c6-bc5e-44e5-a189-926caab9b7f7-1add/screen/b792d863-1a34-4c91-bb55-bd41e92e4433/

SP時
https://xd.adobe.com/view/4f8e11c6-bc5e-44e5-a189-926caab9b7f7-1add/screen/d4adce57-19a0-4601-93ae-fbe57cb696ff/sp-TOP-

## 画像データ
https://drive.google.com/drive/u/2/folders/1TCRgautMcfRWUNS5IzVT5v11gVCbPXI5

**Comment by ririko25** [comment]
以下の修正対応お願いします！



## PC

OKです！


## SP

- [ ] 見出しのテキストサイズがpc時のままになっているので、spサイズに修正お願いします！

コーディング
![スクリーンショット 2020-07-08 15 30 13](https://user-images.githubusercontent.com/29808916/86885318-0255f480-c130-11ea-9fe6-1c90d8199261.png)


- [ ] 見出し、写真要素、テキストが全て同じ横幅で表示される（左右に同じ値だけpaddingがつく）ように修正お願いします！

コーディング
![スクリーンショット 2020-07-08 15 32 09](https://user-images.githubusercontent.com/29808916/86885407-35988380-c130-11ea-8b8c-6646670269c0.png)


カンプ
![スクリーンショット 2020-07-08 15 30 36](https://user-images.githubusercontent.com/29808916/86885374-24e80d80-c130-11ea-9d35-f37a24632f2b.png)
