### ISSUE TITLE
tailwindcssコーディング方法共通化

### ISSUE THREAD

**Issue by ririko25** [chatbox-inc/chatbox2020#26]
## ルール

共通化されるボタンのような要素はコンポーネント化して、tailwindのクラスのみを使用
position指定など、tailwindで実現出来ない場合のみcomponent内にcssを記述しても良い。

## コンポーネント

グローバルなコンポーネントには役割に応じてprefixをつける。

UI系: ボタン -> UIButton.vue
Layout系: ヘッダー -> LHeader

**Comment by mikakane** [comment]
指針:

Vue のコンポーネントを使う

https://tailwindcss.com/docs/extracting-components

**Comment by mikakane** [comment]
> For small components

小さいものは CSS にしてもいいよ。

**Comment by mikakane** [comment]
グローバルな CSS はなし

vue 内の CSS はギリあり
