### ISSUE TITLE
【デザイン】TOPページ

### ISSUE THREAD

**Issue by ririko25** [chatbox-inc/chatbox2020#7]
## 概要

TOPページのデザイン修正とセクション追加

## デザイン修正
- [x] Creationの縦書き文字の修正
- [x] spにした場合タイトルなど大きい文字が改行されてバランスが崩れてしまう部分の修正

## セクション追加
- [x] お知らせの追加(テキストで新規5件ほど。イベントがあるごとに更新される)
- [x] 採用情報の追加(直接wantedlyへ飛ぶ)
- [x] companyはcontactと同じ形式にして専用ページへ飛ばす

**Comment by NaNagaiShiho** [comment]
## デザイン修正
- [ ] Creationの縦書き文字の修正
- [ ] spにした場合タイトルなど大きい文字が改行されてバランスが崩れてしまう部分の修正

一旦現場で

**Comment by NaNagaiShiho** [comment]
## spデザイン変更

<img width="282" alt="スクリーンショット 2020-07-02 17 14 57" src="https://user-images.githubusercontent.com/58157082/86333954-8f5c0200-bc87-11ea-86fb-e65f50c7d8cf.png">
